# Site settings

title: Strata # Title of your site
email: armel.fauveau@globalis-ms.com # Your contant email

description: "GLOBALIS Ⓖ co-founder/CTO & OpenGoodies partner, Web, Security, Performance, Apple  Addict, Geek Life, Astronomy, Arduino, RX, Nature, Fly Fishing and more."
keywords: "Apache, Nginx, PHP, MySQL, MariaDB, Python, Web, HTML, CSS, Swift, Security, Performance, Apple, Geek Life, Astronomy, Arduino, RX, Nature, Fly Fishing."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     fauveauarmel  # Replace this with your Twitter username
github_username:      armel  # Replace this with your GitHub username
linkedin_username:    fauveauarmel  # Replace this with your LinkedIn username

# Build settings
markdown: kramdown
