#!/usr/bin/env python3
"""Generate the JavaScript fallback used when UV Studio runs from file://."""

from __future__ import annotations

import base64
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "factory-assets.js"
ASSETS = (
    (
        "assets/factory/K1_External_Flash_Factory_Reconstructed.bin",
        "K1_External_Flash_Factory_Reconstructed.bin",
        0x200000,
        "a2383aa050dc0963fee7b7c99692b8330d9455a6bbb2bb7498b2bba4174c9d55",
    ),
    (
        "assets/factory/K5V3_External_Flash_Factory_Reconstructed.bin",
        "K5V3_External_Flash_Factory_Reconstructed.bin",
        0x200000,
        "b85c8066a1b0885d1cf3e430533f45c9c8ea91c8b936a94aba99221fd1bff79b",
    ),
    (
        "assets/factory/quansheng.k1.stock.firmware.v7.03.01.bin",
        "quansheng.k1.stock.firmware.v7.03.01.bin",
        71268,
        "55ec0daffc5668bdb41dcc118475d7e6e23ad953d70f57a9bca64a6202734ba0",
    ),
    (
        "assets/factory/quansheng.k5v3.stock.firmware.v7.00.11.bin",
        "quansheng.k5v3.stock.firmware.v7.00.11.bin",
        71712,
        "f4e5264a6f9a5436a6c75f7b217c60ba002cec04928f247392b9968c5c9458cb",
    ),
)


def main() -> None:
    encoded_assets = {}
    for url, filename, expected_size, expected_hash in ASSETS:
        data = (ROOT / filename).read_bytes()
        actual_hash = hashlib.sha256(data).hexdigest()
        if len(data) != expected_size or actual_hash != expected_hash:
            raise ValueError(f"{filename}: unexpected size or SHA-256")
        encoded_assets[url] = base64.b64encode(data).decode("ascii")

    payload = json.dumps(encoded_assets, separators=(",", ":"))
    OUTPUT.write_text(
        "// Generated by build_factory_assets.py; do not edit manually.\n"
        "window.UVStudioFactoryAssets=Object.freeze(" + payload + ");\n",
        encoding="utf-8",
    )
    print(f"{OUTPUT.name}: {OUTPUT.stat().st_size} bytes")


if __name__ == "__main__":
    main()
